name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  productNamespacePrefix: "Punchclock"

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: none
    uses: reactiveui/actions-common/.github/workflows/workflow-common-setup-and-build.yml@main
    with:
      configuration: Release
      productNamespacePrefix: "Punchclock"
      useVisualStudioPreview: false
      useMauiCheckDotNetTool: false
      installWorkflows: false
      installWindowsSdk: false
      dotNetBuild: true
      solutionFile: "Punchclock.sln"
